/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example.lib;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
    }
}
