version: '3.1'

services:

  mongo:
    image: mongo
    expose:
      - 27017
    ports:
      - 27017:27017

  app:
    image: openjdk
    command: ["./gradlew", "run"]
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 8080:8080
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_COLLECTION: data

